--Allowed textures to change

TexturePermissions =
{
	["assembling-machine-1"] = true,
	["assembling-machine-2"] = true,
	["assembling-machine-3"] = true,
	["basic-beacon"] = true,
	["basic-inserter"] = true,
	["basic-mining-drill"] = true,
	["basic-splitter"] = true,
	["basic-transport-belt"] = false,  --WIP
	["basic-transport-belt-to-ground"] = true,
	["basic-accumulator"] = true,
	["big-electric-pole"] = true,
	["biter-spawner"] = false, --1GB
	["boiler"] = false,  --WIP
	["burner-inserter"] = true,
	["burner-mining-drill"] = true,
	["car"] = false, --1GB
	["cargo-wagon"] = false, --1GB
	["chemical-plant"] = true,
	["coal"] = true,
	["combinator"] = true,
	["defender"] = true,
	["destroyer"] = true,
	["distractor"] = true,
	["construction-robot"] = true,
	["copper-ore"] = true,
	["curved-rail"] = false,  --WIP
	["decorative"] = false,  --1GB
	["diesel-locomotive"] = false, -- 1GB
	["electric-furnace"] = true,
	["express-splitter"] = true,
	["express-transport-belt-to-ground"] = true,
	["fast-inserter"] = true,
	["fast-splitter"] = true,
	["fast-transport-belt-to-ground"] = true,
	["gate"] = true,
	["gun-turret"] = false, -- WIP
	["iron-chest"] = true,
	["iron-ore"] = true,
	["lab"] = true,
	["laser-turret"] = false, --WIP
	["logistic-chest-passive-provider"] = true,
	["logistic-chest-active-provider"] = true,
	["logistic-chest-storage"] = true,
	["logistic-chest-requester"] = true,
	["logistic-robot"] = true,
	["long-handed-inserter"] = true,
	["medium-electric-pole"] = true,
	["offshore-pump"] = true,
	["oil-refinery"] = true,
	["pipe"] = true,
	["pipe-covers"] = true,
	["pipe-to-ground"] = true,
	["pumpjack"] = true,
	["radar"] = true,
	["rail-chain-signal"] = true,
	["player"] = false, --cropcache.dat -- 1GB
	["rail-signal"] = true,
	["roboport"] = true,
	["rocket-silo"] = false, --1GB
	["rocket-silo-rocket"] = false, --1GB
	["small-electric-pole"] = true,
	["small-lamp"] = true,
	["small-pump"] = true,
	["smart-chest"] = true,
	["smart-inserter"] = true,
	["solar-panel"] = true,
	["spitter-spawner"] = false,  --1GB
	["steam-engine"] = false, --1GB
	["steel-chest"] = true,
	["steel-furnace"] = true,
	["stone"] = true,
	["stone-furnace"] = true,
	["stone-wall"] = true,
	["storage-tank"] = true,
	["straight-rail"] = false,  --WIP
	["substation"] = true,
	["tank"] = false, --1GB
	["train-stop"] = true,
	["tree"] = false, --WIP 1GB
	["wooden-chest"] = true
	
	-- Fixed pipe artifact
}